# Streamlit Secrets Configuration
OPENROUTER_API_KEY = "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"
WHISPER_MODEL = "base"
DOWNLOAD_DIR = "downloads/"
MAX_FILE_SIZE_MB = 50
SUPPORTED_LANGUAGES = ["english", "spanish", "french", "german", "portuguese", "italian"]
