# Streamlit Secrets Configuration
OPENROUTER_API_KEY = "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 "
WHISPER_MODEL = "base"
DOWNLOAD_DIR = "downloads/"
MAX_FILE_SIZE_MB = 75
SUPPORTED_LANGUAGES = ["english", "spanish", "french", "german", "portuguese", "italian"]